version: 2.1 # use CircleCI 2.1
# orbs:
#   node: circleci/node@1.0.1

orbs:
  aws-s3: circleci/aws-s3@1.0.10

executors:
  node-11-executor:
    docker:
      - image: circleci/node:11.0
commands:
  where_am_i:
    description: "Show current files"
    steps:
      - run: ls
  install_npm:
    description: "Install the latest npm version"
    steps:
      - run: 'sudo npm install -g npm@latest'
  install_dependencies:
    description: "Install project dependencies"
    steps:
      - run: npm install
  test_code:
    description: "Test the code"
    steps:
      - run: npm test
  test_coverage:
    description: "Check the code coverage"
    steps:
      - run: npm run coverage
  build_project:
    description: "Build the project"
    steps:
      - run: npm run build
  deploy_project:
    description: "deploy the project"
    steps:
      - run: npm run deploy


jobs:
  build:
    executor: node-11-executor
    steps:
      - checkout
      - where_am_i
      - install_npm
      - install_dependencies
      - test_code
      - test_coverage
      - build_project
      - where_am_i
      - deploy_project
